export const books = [
  {
    id: 1,
    title: "Atomic Habits",
    author: "James Clear",
    category: "Self Help",
    price: 16.99,
    image: "https://example.com/atomic.jpg",
    stock: 12,
    rating: 4.9,
    reviewCount: 240,
    isTopPick: true,
  },
  {
    id: 2,
    title: "Deep Work",
    author: "Cal Newport",
    category: "Productivity",
    price: 14.99,
    image: "https://example.com/deep.jpg",
    stock: 8,
    rating: 4.8,
    reviewCount: 190,
    isTopPick: true,
  },
  {
    id: 36,
    title: "The Midnight Library",
    author: "Matt Haig",
    category: "Fiction",
    price: 13.99,
    image: "https://example.com/midnight.jpg",
    stock: 5,
    rating: 4.6,
    reviewCount: 160,
    isTopPick: false,
  },
];
